CREATE DATABASE IMOBILIARIA;

USE IMOBILIARIA;

CREATE TABLE IMAGEM(
	ID_IMAGEM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	IMAGEM LONGBLOB NOT NULL
);

CREATE TABLE TIPO_IMOVEL(
	ID_TIPO_IMOVEL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME_TIPO_IMOVEL VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_LOCALIDADE(
	ID_TIPO_LOCALIDADE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME_TIPO_LOCALIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_NEGOCIO(
	ID_TIPO_NEGOCIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME_TIPO_NEGOCIO VARCHAR(50) NOT NULL
);

CREATE TABLE IMOVEL(
	ID_IMOVEL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    N_COMODOS INT NOT NULL,
    IMAGEM INT,
    ID_TIPO_IMOVEL INT,
    ID_TIPO_LOCALIDADE INT,
    ID_TIPO_NEGOCIO INT,
    CONSTRAINT FK_IMAGEM FOREIGN KEY (IMAGEM) REFERENCES IMAGEM(ID_IMAGEM),
	CONSTRAINT FK_ID_TIPO_IMOVEL FOREIGN KEY (ID_TIPO_IMOVEL) REFERENCES TIPO_IMOVEL(ID_TIPO_IMOVEL),
    CONSTRAINT FK_ID_TIPO_LOCALIDADE FOREIGN KEY (ID_TIPO_LOCALIDADE) REFERENCES TIPO_LOCALIDADE(ID_TIPO_LOCALIDADE),
    CONSTRAINT FK_ID_TIPO_NEGOCIO FOREIGN KEY (ID_TIPO_NEGOCIO) REFERENCES TIPO_NEGOCIO(ID_TIPO_NEGOCIO)
);
