DROP TABLE IF EXISTS BD0503.USUARIO;

CREATE TABLE BD0503.USUARIO (
    ID_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    GENERO VARCHAR(30) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    NUMERO INTEGER NOT NULL,
    CEP INTEGER NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

INSERT INTO BD0503.USUARIO (NOME, GENERO, NASCIMENTO, EMAIL, RUA, BAIRRO, CIDADE, ESTADO, PAIS, NUMERO, CEP)
VALUES ('Bianca Maccarini', 'Feminino', '1999-01-31', 'bibis@gmail.com', 'Rua Henri Seb', 'amara', 'Videira', 'SC', 'Brasil', 49, 89560000);
