-- INNER JOIN
-- Retorna os registros quesao comuns as duas tabelas

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, 
    COUNT(INF.COD_PRODUTO) AS QTD,
    SUM(INF.VL_TOTAL) AS TOTAL
FROM 
	NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
ON NF.NRO_NOTA = INF.NRO_NOTA
GROUP BY NF.NRO_NOTA, NF.NM_CLIENTE
ORDER BY QTD DESC;

INSERT INTO `NOTA_FISCAL`(
	NM_CLIENTE
    , END_CLIENTE
    , NM_VENDEDOR
    , VL_TOTAL)
VALUES ('Smeagol', 'Pantano', 'Sauron', 99.00 );

SELECT + FROM NOTA_FISCAL
WHERE NM_CLIENTE = 'Smeagol';


INSERT INTO `NOTA_FISCAL`(
	NM_CLIENTE
    , END_CLIENTE
    , NM_VENDEDOR
    , VL_TOTAL)
VALUES ('Gimly', 'montanha', 'thorin', 9999.00);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Queijo', 'kg', '30');
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Copa', 'kg', '70');




-- INNER JOIN

SELECT 
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
INNER JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;
	
-- LEFT JOIN
-- RETORNA OS REGISTROS QUE ESTAO A ESQUERDA MESMO QUE  NAO ESTEJAM A DIREITA 
-- E OS REGISTROS DA TABELA A DIREITA QUE SAO COMUNS A ELAS.

SELECT 
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
LEFT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
LEFT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;


-- RIGHT JOIN
-- USAMOS PARA EXIBIR OS REGISTROS QUE ESTAO NA TABELA
-- A DIREITA (MESMO QUE NAO ESTEJAM NA TABERLA A ESQUERDA)
-- E OS REGISTROS DA TABELA A ESQUERDA
-- QUE SAO COMUNSA DIREITA.


SELECT 
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
RIGHT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
RIGHT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

