-- CRIAR NOVO BD
CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O BD
USE GREENHOUSE;

-- CRIANDO TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
  `PLANT_NAME` CHAR(30) NOT NULL,
  `SENSOR_VALUE` FLOAT DEFAULT NULL,
  `SENSOR_EVENT` TIMESTAMP NOT NULL
     DEFAULT CURRENT_TIMESTAMP ON
     UPDATE CURRENT_TIMESTAMP,
  `SENSOR_LEVEL` CHAR (5) DEFAULT NULL,
  PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERCAO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('BABOSA', 15, 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('GIRASOL', 45, 'MED');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('CIDREIRA', 35, 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('SAMANBAIA', 23, 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('LIRIO', 9, 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('FICUS', 13, 'MED');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('DALIA', 2, 'HIGH');  
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('AVENCA', 47, 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('BAMBU', 51, 'MED');

-- EXECUTANDO COMANDOS DQL
-- consultando tudo da tabela
SELECT * FROM `GREENHOUSE`.`PLANTS`;

SELECT PLANT_NAME, SENSOR_EVENT FROM GREENHOUSE.PLANTS;

-- APLICAR FILTROS NOS REGISTROS DE DADOS
SELECT * FROM PLANTS WHERE SENSOR_LEVEL = 'HIGH' AND SENSOR_VALUE >= 10 AND SENSOR_VALUE <= 20;

SELECT * FROM `PLANTS` WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');

-- CLAUSOLA DE ORDENACAO
SELECT * FROM `PLANTS` WHERE SENSOR_LEVEL < 420 ORDER BY `SENSOR_VALUE` DESC;

-- CLAUSOLA FUNCOES DE AGRUPAMENTO
SELECT COUNT(*), `SENSOR_LEVEL` FROM `PLANTS` GROUP BY `SENSOR_LEVEL`;

-- TOP
SELECT * FROM PLANTS WHERE SENSOR_LEVEL IS NOT NULL LIMIT 3;

-- MIN E MAX
SELECT MIN(SENSOR_VALUE)
FROM PLANTS;

SELECT MAX(SENSOR_VALUE)
FROM PLANTS;

-- COUNT
SELECT COUNT(*)
FROM PLANTS;

-- SUM
SELECT SUM(SENSOR_VALUE) FROM PLANTS;

-- AVG
SELECT AVG(SENSOR_VALUE) FROM PLANTS;
-- LIKE
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE 'G_R_S__';
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE '%a%o%a'; -- TODOS QUE TEM AS LETRAS
SELECT PLANT_NAME FROM PLANTS WHERE PLANT_NAME LIKE '_a_o_a'; -- APARECE SÓ O NOME DA PLANTA (COM O * APARECE TUDO)
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE 'a%'; -- AS QUE COMEÇAM COM A LETRA A
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE '%a%'; -- AS QUE TEM A LETRA A NA PALAVRA
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE '%a'; -- AS QUE TEM A LETRA A NO FINAL DA PALAVRA

-- COMANDO PARA ATUALIZAR REGISTROS DE DADOS

SELECT * FROM PLANTS;
UPDATE PLANTS SET SENSOR_LEVEL = 90, SENSOR_LEVEL = 'HIGH' WHERE PLANT_NAME = "BABOSA";

-- APAGANDO REGISTRO DA TABELA DO BANCO DE DADOS 
DELETE FROM PLANTS WHERE PLANT_NAME = 'BAMBU';