CREATE DATABASE DADOS_CADASTRAIS_DO_FUNCIONARIO;

USE DADOS_CADASTRAIS_DO_FUNCIONARIO;

CREATE TABLE 
MATRICULA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
DATA_NASC INT NOT NULL,
NACIONALIDADE VARCHAR (100) NOT NULL,
SEXO VARCHAR (100) NOT NULL,



